# Changes here will be overwritten by Copier
_commit: v0.1.2
_src_path: gh:igembitsgoa/igem-wiki-starter
author: Bram Spanoghe
email: Bram.Spanoghe@UGent.be
iGEM_official_team_name: UGent_Belgium
iGEM_team_name: Vsycle
year: 2020
